apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mongodb-express-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mongodb-express
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 10
